server:
  port: 18083

spring:
  application:
    name: sentinel-example

spring:
  cloud:
    sentinel:
      transport:
        dashboard:  127.0.0.1:8080

management:
  endpoints:
    web:
      exposure:
        include: *