server:
  port: 9091

spring:
  application:
    name: dubbo-provider
  boot:
    admin:
      client:
        url: http://127.0.0.1:8060  # admin的地址,不加http会注册失败
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: "@dev_namespace@"
  # bean会覆盖之前相同名称的bean, Spring Boot 2.1 需要设定
  main:
    allow-bean-definition-overriding: true

# 应用名
dubbo:
  application:
    id: service-provider
    name: service-provider
  # 扫描dubbo服务(@Service.. @Reference..)
  scan:
    base-packages: com.comic.blank.service
  # 通信协议
  protocol:
    id: dubbo
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  # 注册中心
  registry:
    id: dubboRegistry
    timeout: 5000
    address: nacos://127.0.0.1:8848

# 给spring-admin中显示的服务添加版本号，从pom中取
info:
  version: @project.version@