server:
  port: 8088
  servlet:
    context-path: /order

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: be8aca6a-8ab2-4845-88cf-772a06f7f540
