server:
  port: 8081
  servlet:
    context-path: /feign

spring:
  application:
    name: feign-provider
  boot:
    admin:
      client:
        url: http://127.0.0.1:8060  # admin的地址,不加http会注册失败
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: "@dev_namespace@"

# 给spring-admin中显示的服务添加版本号，从pom中取
info:
  version: @project.version@