server:
  port: 8081
  servlet:
    context-path: /feign

spring:
  application:
    name: feign-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: be8aca6a-8ab2-4845-88cf-772a06f7f540
