server:
  port: 9090

spring:
  application:
    name: dubbo-consumer
  boot:
    admin:
      client:
        url: http://127.0.0.1:8060  # admin的地址,不加http会注册失败
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: "@dev_namespace@"
  # bean会覆盖之前相同名称的bean
  main:
    allow-bean-definition-overriding: true

# 应用名
dubbo:
  application:
    id: service-consumer
    name: service-consumer
  # 扫描dubbo服务(@Service.. @Reference..)
  scan:
    base-packages: com.comic.blank.controller
  # 通信协议
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  # 注册中心
  registry:
    id: dubboRegistry
    timeout: 5000
    address: 127.0.0.1:8848
    protocol: nacos

# 给spring-admin中显示的服务添加版本号，从pom中取
info:
  version: @project.version@