server:
  port: 8083

spring:
  redis:
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 8
        max-wait: 100000
    host: 127.0.0.1
    timeout: 3000
    port: 6379
    password: "12345"